const CATS = [
  {
    name: 'Fluffikins',
    breed: 'Orange tabby',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 8,
  },
  {
    name: 'Blizzard',
    breed: 'Calico',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 7,
  },
  {
    name: 'Garfield',
    breed: 'Main coon',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 4,
  },
  {
    name: 'Vanilla',
    breed: 'Siberian',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 1,
  },
  {
    name: 'Savannah',
    breed: 'Scottish fold',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 10,
  },
  {
    name: 'Sudoku',
    breed: 'Munchkin',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 2,
  },
  {
    name: 'Brownie',
    breed: 'Ragdoll',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 9,
  },
  {
    name: 'Ms Aloof',
    breed: 'British Shorthair',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 4,
  },
  {
    name: 'Winnie',
    breed: 'Sphynx',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 2,
  },
  {
    name: 'Puffins',
    breed: 'Bengal',
    url: 'https://placekitten.com/800/600',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    age: 6,
  },
];
